name: ASDI-SMSL-DEMO-DELTA
channels:
- conda-forge
- defaults
dependencies:
- python>=3.8
- numpy<=1.21
- matplotlib
- jupyter
- netcdf4
- xarray
- scipy
- boto
- boto3
- arm_pyart
- cartopy
- pooch
- gdal
- datacube
- rioxarray
- intake
- intake-xarray
- rasterio
- datashader
- s3fs
- hvplot
- geopandas 
- geoviews